# Generated by Django 3.1.5 on 2021-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
