# Generated by Django 3.1.5 on 2021-02-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimblog', '0005_auto_20210205_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
